# datasource
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ework?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver

  application:
    name: mybatisAuto

  session:
    store-type: none

  redis:
    host: 127.0.0.1
    port: 6379

server:
  port: 8089

#mybatis  sql
logging:
  level:
    com:
      hiyouka:
        source:
          mapper: debug
          respository: debug
    org:
      springframework: trace

config:
  port: 8001




