# datasource
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ework?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root@root
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: mybatisAuto

  session:
    store-type: none

  redis:
    host: 127.0.0.1
    port: 6379

server:
  port: 8991

#mybatis  sql
logging:
  level:
    com:
      hiyouka:
        source:
          mapper: debug
          respository: debug

config:
  port: 8001




