## datasource
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ework?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jta:
    enabled: true
  application:
    name: aopAuto

  session:
    store-type: none

  redis:
    host: 127.0.0.1
    port: 6379
### is use cglib proxy
  aop:
    proxy-target-class: false

server:
  port: 8992

#mybatis  sql
logging:
  level:
    com:
      hiyouka:
        source:
          mapper: debug
          respository: debug
#    com:
#      hiyouka:
#        source: trace
    org:
      springframework: trace


config:
  port: 8001
ios:
  key:
    video: 123
    movie: 123




